version: '3.0'

services:
  tensorflow:
    container_name: 'tf-2.16'
    image: tensorflow/tensorflow:2.16.1
    # build: .
    volumes:
      - .:/app
      - ./io:/io
    working_dir: /app 
    environment:
      - img_size=512
      - bsize=6
      - model_path="u2net-512.keras"

    command: python3 main.py

    stdin_open: true
    tty: true
